version: 1.0
provider:
  name: openfaas
  gateway: http://gateway.myfaas.flyingfang.com
functions:
  hello:
    lang: node10-express
    handler: ./hello
    image: xflying/hello:latest

version: 1.0
provider:
  name: openfaas
  gateway: http://gateway.myfaas.flyingfang.com
functions:
  node-http-server:
    lang: node10-express
    handler: ./node-http-server
    image: xflying/node-http-server:latest
    labels:
      com.openfaas.scale.min: 1
      com.openfaas.scale.max: 10
      com.openfaas.scale.factor: 50

